stages:
  - build

build:docker:scala:
  stage: build
  image: docker:18.06.3-ce
  variables:
    EXCLUDE_DOCKERDIR: "openjdk/11/jdk/alpine openjdk/11/jdk/slim openjdk/8/jdk/alpine openjdk/12/jdk/alpine scala-sbt/2.11-0.13/alpine"
  script:
    - apk add --no-cache make git wget bash groff less python py-pip
    - pip install awscli
    - make build
  only:
    - trigger
    - master
  tags:
    - full360


build:docker:java:
  stage: build
  image: docker:18.06.3-ce
  variables:
    EXCLUDE_DOCKERDIR: "scala-sbt/11-2.12-1.2/slim scala-sbt/12-2.12-1.2/alpine"
  script:
    - apk add --no-cache make git wget bash groff less python py-pip
    - pip install awscli
    - make build
  only:
    - trigger
    - master
  tags:
    - full360
