name: OpenJDK 12 Images Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  openjdk-12:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Alpine OpenJDK 12
        uses: docker/build-push-action@v2
        with:
          context: ./openjdk/12/jdk/alpine
          file: ./openjdk/12/jdk/alpine/Dockerfile
          pull: true
          push: true
          tags: |
            full360/openjdk:12-alpine
            full360/openjdk:12-jdk-alpine

      - name: Build Scala 2.12 OpenJDK 12
        uses: docker/build-push-action@v2
        with:
          context: ./scala-sbt/12-2.12-1.2/alpine
          file: ./scala-sbt/12-2.12-1.2/alpine/Dockerfile
          pull: true
          push: true
          tags: |
            full360/scala-sbt:12-2-1-jdk-alpine
            full360/scala-sbt:12-2.12-1.2-jdk-alpine
