name: OpenJDK 11 Images Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - LICENSE
      - README.md
  schedule:
    - cron: 0 0 * * 0

jobs:
  openjdk-11:
    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Slim OpenJDK 11
        uses: docker/build-push-action@v2
        with:
          context: ./openjdk/11/jdk/alpine
          file: ./openjdk/11/jdk/alpine/Dockerfile
          pull: true
          push: true
          tags: |
            full360/openjdk:11-slim
            full360/openjdk:11-jdk-slim

      - name: Build Scala 2.12 OpenJDK 11
        uses: docker/build-push-action@v2
        with:
          context: ./scala-sbt/11-2.12-1.2/slim
          file: ./scala-sbt/11-2.12-1.2/slim/Dockerfile
          pull: true
          push: true
          tags: |
            full360/scala-sbt:11-2-1-jdk-slim
            full360/scala-sbt:11-2.12-1.2-jdk-slim
